### ISSUE TITLE
Failure to export survey, "Error generating file: null" message appears.

### ISSUE THREAD

**Issue by j-johanness** [openforis/collect#16]
Dear Open Foris Collect, 

I have been unsuccessful in posting a question on the online community support forum, where I am constantly redirected to a page saying "500 Server Error. Sorry, system error.". Thus, I am contacting you via GitHub instead.

Recently, I updated both Collect and Collect Earth to their latest versions (ver 1.8.2 and ver 3.24.21 respectively). I created a new survey (for Collect Earth) in the Survey Designer. After customizing the "Info", "Code List" and "Schema" tabs in the survey, I saved it, and validated it. A popup message confirmed there were no errors in the survey.

However, when I attempt to export this survey (temporary), it would say "Failed". When I try exporting the survey within the survey itself (via the Settings "gear" symbol), an error message "Error generating file: null" appears. I tried uninstalling-reinstalling Collect and Collect Earth, and also recreated the survey on another computer (where Collect and Collect Earth were never downloaded before), the same error message appears.

Upon further investigation, this newly made survey is not the only one I am unable to export. It turns out that I am unable to export any and all surveys within my List of Surveys. This includes surveys created in previous versions of Collect, as well as template surveys such as the UMD Brazil and Congo example surveys available on the Collect webpage (I could import them into the Survey Designer, but could not export them).

Hoping for your kind advice on the matter. Attached is the log file for Collect. I am able to export it for Collect Desktop and Collect Mobile, but not Collect Earth. I am also able to import the file previously exported for Collect Desktop into the Survey Designer, but am unable to export it to Collect Earth.

Warmest regards, 
J Johanness

[collect_server-05-17-2019-1.log](https://github.com/openforis/collect/files/3190166/collect_server-05-17-2019-1.log)

**Comment by fefrain** [comment]
Dear J Johannes,
Can you please share with me the log files folder in c:\Users\YOUR_USER\OpenForis\Collect\logs and  your collect.db file (the database file) that is in c:\Users\YOUR_USER\OpenForis\Collect\data ? (This file contains all your surveys/data and I will be able to see what's going on).
If you can please zip everything and share it through Google Drive or similar.
Many thanks,
Stefano
________________________________

**Comment by j-johanness** [comment]
Hi there Stefano, 

Thank you for replying. I attach a zipped folder for C:\Users\YOUR_USER\OpenForis\Collect\logs. 
[logs.zip](https://github.com/openforis/collect/files/3190452/logs.zip) There is no folder that matches the path c:\Users\YOUR_USER\OpenForis\Collect\data, and I am unable to find the collect.db file.

Note that on top of updating it from a previous version (before ver 3.24.20), I also uninstalled and then re-installed the program. Am I supposed to see a folder called 'data'? Currently, if I open Collect, in the List of Surveys, I can see all past and present surveys created and/or imported by me. The only folders in the directory are as follows;

![Capture](https://user-images.githubusercontent.com/43123250/57912216-56fb3800-78bc-11e9-84a7-b164b29e49bc.JPG)

Warmest regards, 
J Johanness

**Comment by fefrain** [comment]
Hi J Johannes,
I was talking about another folder, it should be in C:\Users\YOURUSERNAME\OpenForis\Collect\data , not in C:\OpenForis\Collect...!
Anyway, the log files are enough, we already discovered where the problem is.
We will release a new version of Collect asap.
Many thanks,
Stefano

________________________________

**Comment by j-johanness** [comment]
Hi there Stefano, 

Thank you very much for identifying the problem, and apologies for navigating to the wrong directory! In the event that you require the 'data' folder, I have zipped it and attach it here. 

[data.zip](https://github.com/openforis/collect/files/3190495/data.zip)

Warmest regards, 
J Johanness

**Comment by fefrain** [comment]
Hi J Johannes,
Please update Collect to the latest version.
Thanks!
Stefano
________________________________

**Comment by j-johanness** [comment]
Hi there Stefano,

I updated Collect, and attempted to start it. An error message popped up before it could start. The popup says;

java.lang.RuntimeException: java.io.IOException: Error deleting folder C:\OpenForis\Collect\webapps\collect: Unable to delete file: C:\OpenForis\Collect\webapps\collect\WEB-INF\lib\zweb-6.5.1.1.jar. Please delete it manually and start Collect again
	at org.openforis.collect.controlpanel.CollectControlPanelController.initialize(CollectControlPanelController.java:148)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2548)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2425)
	at org.openforis.collect.controlpanel.CollectControlPanel.start(CollectControlPanel.java:34)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$162(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$175(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: Error deleting folder C:\OpenForis\Collect\webapps\collect: Unable to delete file: C:\OpenForis\Collect\webapps\collect\WEB-INF\lib\zweb-6.5.1.1.jar. Please delete it manually and start Collect again
	at org.openforis.collect.controlpanel.CollectControlPanelController.deleteBrokenTemporaryFiles(CollectControlPanelController.java:399)
	at org.openforis.collect.controlpanel.CollectControlPanelController.initialize(CollectControlPanelController.java:130)
	... 12 more
Caused by: java.io.IOException: Unable to delete file: C:\OpenForis\Collect\webapps\collect\WEB-INF\lib\zweb-6.5.1.1.jar
	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2381)
	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1679)
	at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1575)
	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2372)
	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1679)
	at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1575)
	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2372)
	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1679)
	at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1575)
	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2372)
	at org.openforis.collect.controlpanel.CollectControlPanelController.deleteBrokenTemporaryFiles(CollectControlPanelController.java:393)
	... 13 more

**Comment by j-johanness** [comment]
Dear Stefano, 

After facing that earlier problem (the one I notified you an hour ago), I restarted Collect. Now, I am able to export the survey I recently created, and successfully open it in Collect Earth to assess my plots. I am also pleased to report that I can export other surveys for Collect Earth as per normal, whether it is from the List of Surveys page or within the survey itself (using the Settings symbol).

Thank you for your assistance. Only one other minor issue remains, and that is that even after using the auto updater to get Collect to the latest version (currently ver 3.24.22), there is a prompt at the bottom showing that the version I am using is not the latest one. However, upon launching the auto updater, there was indeed no update available. 

![Capture2](https://user-images.githubusercontent.com/43123250/57966713-4f08ca00-7988-11e9-81f5-2d0ead11dfee.JPG)

Other than that, everything seems to be back in order. Thank you once again Stefano for promptly aiding me. I express my utmost gratitude to you, as I was not expecting such a quick and efficient reply here on GitHub as opposed to the online community support forum. Thank you and have a nice day.

Warmest regards, 

J Johanness

**Comment by msuber** [comment]
Hi Stefano, 
I´m in the same situation as it was Johanness, but I also have the crew in the field waiting for starting sampling plots and rain season approaching. 
I have the latest version of Collect 4.0.28, just dowloaded when trying any path..
I have introduced some modifications to a recent survey that was working, when i started receiving this error.
Is there any chance to get a super fat reply? every day counts here.. 
Thanks!
Marta
