### ISSUE TITLE
jOOQ DataAccesException: when adding plot and importing backup with existing plots

### ISSUE THREAD

**Issue by phillipgajadhar** [openforis/collect#44]
**Environment**
- Open Foris Collect Version: 4.0.29
- Tomcat version 8 on JRE 11 using Docker ([https://hub.docker.com/_/tomcat](https://hub.docker.com/_/tomcat)).
- PostgreSQL 9 using Docker ([https://hub.docker.com/_/postgres](https://hub.docker.com/_/postgres)).
- Notable JARs: commons-dbcp-1.4.jar, commons-pool-1.6.jar, sqlite-jdbc-3.34.0.jar, and postgresql-9.4.1212.jar.

**Steps to reproduce**
Add new plot or import backup with existing plots

**Exception logged**

28-Sep-2021 17:33:32.173 SEVERE [SimpleAsyncTaskExecutor-42] org.openforis.concurrency.Worker.logError Error running worker (status: RUNNING): SQL [select count(*) from "collect"."ofc_sampling_design" where ("collect"."ofc_sampling_design"."survey_id" = ? and "collect"."ofc_sampling_design"."level1" = ? and "collect"."ofc_sampling_design"."level2" is not null and "collect"."ofc_sampling_design"."level3" is null) order by "collect"."ofc_sampling_design"."id" asc]; ERROR: column "ofc_sampling_design.id" must appear in the GROUP BY clause or be used in an aggregate function
  Position: 280
	org.jooq.exception.DataAccessException: SQL [select count(*) from "collect"."ofc_sampling_design" where ("collect"."ofc_sampling_design"."survey_id" = ? and "collect"."ofc_sampling_design"."level1" = ? and "collect"."ofc_sampling_design"."level2" is not null and "collect"."ofc_sampling_design"."level3" is null) order by "collect"."ofc_sampling_design"."id" asc]; ERROR: column "ofc_sampling_design.id" must appear in the GROUP BY clause or be used in an aggregate function
  Position: 280
		at org.jooq.impl.Utils.translate(Utils.java:1645)
		at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:661)
		at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:356)
		at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:319)
		at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:306)
		at org.jooq.impl.AbstractResultQuery.fetchOne(AbstractResultQuery.java:440)
		at org.jooq.impl.AbstractResultQuery.fetchOne(AbstractResultQuery.java:408)
		at org.jooq.impl.AbstractResultQuery.fetchOne(AbstractResultQuery.java:414)
		at org.openforis.collect.persistence.SamplingDesignDao.countChildItems(SamplingDesignDao.java:203)
		at org.openforis.collect.persistence.SamplingDesignDao$$FastClassBySpringCGLIB$$5210c7cb.invoke(<generated>)
		at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
		at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
		at org.openforis.collect.persistence.SamplingDesignDao$$EnhancerBySpringCGLIB$$9a29e71b.countChildItems(<generated>)
		at org.openforis.collect.persistence.DatabaseExternalCodeListProvider.hasChildItems(DatabaseExternalCodeListProvider.java:227)
		at org.openforis.collect.persistence.DatabaseExternalCodeListProvider$$FastClassBySpringCGLIB$$10fc7304.invoke(<generated>)
		at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
		at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
		at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
		at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
		at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
		at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
		at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
		at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
		at org.openforis.collect.persistence.DatabaseExternalCodeListProvider$$EnhancerBySpringCGLIB$$43b13466.hasChildItems(<generated>)
		at org.openforis.collect.manager.CodeListManager.hasChildItems(CodeListManager.java:498)
		at org.openforis.collect.manager.CodeListManager.hasItems(CodeListManager.java:360)
		at org.openforis.collect.manager.CodeListManager$$FastClassBySpringCGLIB$$72c1af0e.invoke(<generated>)
		at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
		at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
		at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
		at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
		at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
		at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
		at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
		at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
		at org.openforis.collect.manager.CodeListManager$$EnhancerBySpringCGLIB$$6439bec4.hasItems(<generated>)
		at org.openforis.collect.service.CollectCodeListService.hasItems(CollectCodeListService.java:52)
		at org.openforis.idm.metamodel.validation.MinCountValidator.isAvailableCodeListItems(MinCountValidator.java:79)
		at org.openforis.idm.metamodel.validation.MinCountValidator.evaluate(MinCountValidator.java:56)
		at org.openforis.collect.model.validation.CollectMinCountValidator.evaluate(CollectMinCountValidator.java:30)
		at org.openforis.idm.metamodel.validation.Validator.validateMinCount(Validator.java:59)
		at org.openforis.collect.model.validation.CollectValidator.validateMinCount(CollectValidator.java:133)
		at org.openforis.collect.model.RecordUpdater.validateCardinality(RecordUpdater.java:537)
		at org.openforis.collect.model.RecordUpdater.initializeEntity(RecordUpdater.java:924)
		at org.openforis.collect.model.RecordUpdater.addEntity(RecordUpdater.java:202)
		at org.openforis.collect.model.RecordUpdater.addNode(RecordUpdater.java:179)
		at org.openforis.collect.command.handler.AddNodeCommandHandler.executeForResult(AddNodeCommandHandler.java:16)
		at org.openforis.collect.command.handler.AddNodeCommandHandler.executeForResult(AddNodeCommandHandler.java:9)
		at org.openforis.collect.command.handler.RecordCommandHandler$1$1.execute(RecordCommandHandler.java:72)
		at org.openforis.concurrency.Worker.run(Worker.java:103)
		at org.openforis.concurrency.Job.runTask(Job.java:95)
		at org.openforis.concurrency.Job.execute(Job.java:80)
		at org.openforis.concurrency.Worker.run(Worker.java:103)
		at org.openforis.concurrency.SimpleJobManager$2.run(SimpleJobManager.java:120)
		at org.springframework.core.task.SimpleAsyncTaskExecutor$ConcurrencyThrottlingRunnable.run(SimpleAsyncTaskExecutor.java:280)
		at java.base/java.lang.Thread.run(Unknown Source)
	Caused by: org.postgresql.util.PSQLException: ERROR: column "ofc_sampling_design.id" must appear in the GROUP BY clause or be used in an aggregate function
  Position: 280
		at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2565)
		at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2297)
		at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:322)
		at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:481)
		at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:401)
		at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164)
		at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:153)
		at org.apache.commons.dbcp.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:172)
		at org.apache.commons.dbcp.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:172)
		at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:194)
		at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:247)
		at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:342)
		... 57 more

**Comment by SteRiccio** [comment]
fixed with version 4.0.30
